export const DAK_COLUMS = [
    {
        headerName: "Book No",
        field: "book",
        colId: "book",
        filter: 'agTextColumnFilter',
        sortable: true,
        width:350,
        menuTabs: ['filterMenuTab'],
        //   suppressMenu: false ,
    },
    {
        headerName: "Centrak Dak NO",
        field: "centrakDak",
        width:200,
        filter: 'agTextColumnFilter',
        sortable: true
       // suppressSizeToFit:true
        // sortable: true,
        // filter: false,
    },
    {
        headerName: "Dak Title",
        colId: 'dak_title',
        filter: 'agTextColumnFilter',
        sortable: true, 
        field: 'dak_title',
        width:200,
    },
    {
        headerName: "Dak Details",
        colId: 'dak_details',
        filter: 'agTextColumnFilter',
        sortable: true, 
        field: 'dak_details',
        width:200,
    },
    {
        headerName: "Sender",
        colId: 'sender',
        filter: 'agSetColumnFilter',
        sortable: true, 
        field: 'sender',
        width:200,
    },
    {
        headerName: "Receiver",
        colId: 'receiver',
        filter: 'agTextColumnFilter',
        hide:true,
        sortable: true, 
        field: 'receiver',
        width:200,
    },
    // {
    //     headerName: "SenderId",
    //     filter: "agSetColumnFilter",
    //     sortable: true,
    //     hide:true,
    //     width:600,
    //     field: 'senderId',   
    // },
    {
        headerName: "Date",
        colId: 'date',
        filter: 'agTextColumnFilter',
        sortable: true, 
        field: 'date',
        width:200,
    },
    {
        headerName: "Last Updated On",
        colId: 'last_updated_date',
        filter: 'agTextColumnFilter',
        hide:true,
        sortable: true, 
        field: 'last_updated_date',
        width:200,
    },
    {
        headerName: "Last Comment",
        colId: 'comments',
        filter: 'agTextColumnFilter',
        sortable: true, 
        field: 'comments',
        width:200,
    },
    {
        headerName: "Added By",
        colId: 'addedBy',
        filter: 'agSetColumnFilter',
        hide:true,
        sortable: true, 
        field: 'addedBy',
        width:200,
    },
    {
        headerName: "Modified By",
        colId: 'modifiedBy',
        filter: 'agSetColumnFilter',
        hide:true,
        sortable: true, 
        field: 'modifiedBy',
        width:200,
    },



   
]